version: '3.8'

services:
  # SRE AI Agent Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - kubernetes-mcp
    networks:
      - sre-network

  # Frontend (for production builds)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sre-network

  # Kubernetes MCP Server (placeholder - should be running separately)
  kubernetes-mcp:
    image: busybox:latest
    command: ['sh', '-c', 'echo "Kubernetes MCP Server placeholder - implement actual MCP server" && sleep infinity']
    ports:
      - "8080:8080"
    networks:
      - sre-network

networks:
  sre-network:
    driver: bridge

volumes:
  backend_data:
  frontend_build: 