version: '3.8'

services:
  # Tarsy-bot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - kubernetes-mcp
    networks:
      - tarsy-network

  # Tarsy-bot UI (for production builds)
  alert-dev-ui:
    build:
      context: ./alert-dev-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tarsy-network

  # Kubernetes MCP Server (placeholder - should be running separately)
  kubernetes-mcp:
    image: busybox:latest
    command: ['sh', '-c', 'echo "Kubernetes MCP Server placeholder - implement actual MCP server" && sleep infinity']
    ports:
      - "8080:8080"
    networks:
      - tarsy-network

networks:
  tarsy-network:
    driver: bridge

volumes:
  tarsy_backend_data:
  tarsy_ui_build: 